
# --- !Ups

CREATE TYPE BLOCK_EXTRACTION_METHOD_TYPE AS ENUM ('PoW', 'PoS', 'TPoS');

ALTER TABLE blocks
    ADD COLUMN extraction_method BLOCK_EXTRACTION_METHOD_TYPE NOT NULL DEFAULT 'PoW';


# --- !Downs

ALTER TABLE blocks
    DROP COLUMN extraction_method;

DROP TYPE BLOCK_EXTRACTION_METHOD_TYPE;
